---
- name: Include vars
  include_vars:
    file: "{{ item }}"
    name: ENVIRONMENT
  with_items:
    - "vars/local.yml"
  when: connection == "local"


- name: Create .env file
  template:
    src: .env.j2
    dest: "{{ playbook_dir }}/../.env"
  when: connection == "local"


- name: Copy docker-compose.override.yml
  copy:
    src: docker-compose.override.yml
    dest: "{{ playbook_dir }}/../docker-compose.override.yml"
  when: connection == "local"

