---
CHAT_ID:
API_KEY:
BOT_KEY:
BOT_BIND_ADDRESS:
BOT_ADDRESS:
BOT_ID:
BOT_PORT:
BOT_CERT_PATH:
BOT_KEY_PATH:
LOG_PATH:
REDIS_ADDRESS: redis:6379
MONGO_ADDRESS: mongo
MONGO_INITDB_ROOT_USERNAME:
MONGO_INITDB_ROOT_PASSWORD:
MONGO_DATABASE:
